#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from second_attempt
import second_attempt
from second_attempt.lib import clean_data

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'second_attempt_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
    folder_source, _ = split(second_attempt.__file__)
    df = pd.read_csv('{}/data/data.csv.gz'.format(folder_source))
    print('  second_attempt/data/data.csv.gz Loaded')

    res = clean_data(df)
    res.to_csv('out.csv', index=False)
    print('==> out.csv MADE ')
    print('    shape is {}'.format(res.shape))
